import { mkdirSync, readFileSync, readdirSync, writeFileSync, existsSync, renameSync } from "node:fs";
import { join } from "node:path";
import { previewPaste } from "../import/previewPaste";
import type { Correction } from "./corrections";

/**
 * One period on disk: every imported report, keyed by report code. The raw pasted text is kept next to
 * the parsed data, so a parser fix can re-read old reports (PRD: raw reports are never edited).
 * Runs in Node only (vite dev-server middleware), never in the browser.
 */
export interface PeriodFile {
  period: number;
  company: string;
  reports: Record<string, StoredReport>;
}

export interface StoredReport {
  kind: string;
  savedAt: string;
  raw: string;
  parsed: { reportCode: string; title: string; period: number; company: string };
  /** Henri's fixes of misread values, applied on read (see corrections.ts); `raw` and `parsed` stay as imported. */
  corrections?: Correction[];
}

export interface SaveResult {
  jsonPath: string;
  notePath: string;
  period: number;
  reportCode: string;
}

export function saveReport(vaultDir: string, raw: string, now: Date = new Date()): SaveResult {
  const preview = previewPaste(raw);
  if (preview.status !== "ok") throw new Error(preview.status === "error" ? preview.message : "Nothing to save: the text is empty");
  const parsed = preview.report;

  const dataDir = join(vaultDir, "data");
  mkdirSync(dataDir, { recursive: true });
  const jsonPath = join(dataDir, `period-${parsed.period}.json`);
  const file: PeriodFile = existsSync(jsonPath)
    ? JSON.parse(readFileSync(jsonPath, "utf8"))
    : { period: parsed.period, company: parsed.company, reports: {} };

  // A re-import must not wipe Henri's fixes; applyCorrections later flags any that no longer fit.
  const corrections = file.reports[parsed.reportCode]?.corrections;
  file.reports[parsed.reportCode] = { kind: preview.kind, savedAt: now.toISOString(), raw, parsed, ...(corrections && { corrections }) };
  writeAtomic(jsonPath, JSON.stringify(file, null, 2) + "\n");
  const notePath = join(vaultDir, `Period ${file.period}.md`);
  writeAtomic(notePath, periodNote(file));
  return { jsonPath, notePath, period: parsed.period, reportCode: parsed.reportCode };
}

/** Adds one fix to a saved report. */
export function saveCorrection(vaultDir: string, period: number, reportCode: string, correction: Correction): void {
  const jsonPath = join(vaultDir, "data", `period-${period}.json`);
  const file: PeriodFile = JSON.parse(readFileSync(jsonPath, "utf8"));
  const report = file.reports[reportCode];
  // Fixing the same cell again replaces the earlier fix — one value, one fix, last one wins.
  report.corrections = [...(report.corrections ?? []).filter((c) => c.path.join() !== correction.path.join()), correction];
  writeAtomic(jsonPath, JSON.stringify(file, null, 2) + "\n");
}

/** Removes a cell's fix (undo). Unknown paths are fine — nothing to undo. */
export function removeCorrection(vaultDir: string, period: number, reportCode: string, path: Correction["path"]): void {
  const jsonPath = join(vaultDir, "data", `period-${period}.json`);
  const file: PeriodFile = JSON.parse(readFileSync(jsonPath, "utf8"));
  file.reports[reportCode].corrections = (file.reports[reportCode].corrections ?? []).filter(
    (c) => c.path.join() !== path.join(),
  );
  writeAtomic(jsonPath, JSON.stringify(file, null, 2) + "\n");
}

/** Every saved period (data/period-<n>.json), oldest first; [] before the first save. */
export function loadPeriods(vaultDir: string): PeriodFile[] {
  const dataDir = join(vaultDir, "data");
  if (!existsSync(dataDir)) return [];
  return readdirSync(dataDir)
    .filter((name) => /^period-\d+\.json$/.test(name))
    .map((name) => JSON.parse(readFileSync(join(dataDir, name), "utf8")) as PeriodFile)
    .sort((a, b) => a.period - b.period);
}

/** Write to a temp file and rename, so a crash never leaves half a file in the vault. */
function writeAtomic(path: string, content: string): void {
  writeFileSync(`${path}.tmp`, content);
  renameSync(`${path}.tmp`, path);
}

/** The human-readable side of a period (PRD Must 1: "a Markdown note in the vault"). Regenerated on every save. */
export function periodNote(file: PeriodFile): string {
  const codes = Object.keys(file.reports).sort();
  const rows = codes.map((c) => {
    const r = file.reports[c];
    return `| ${c} | ${r.parsed.title} | ${r.savedAt.slice(0, 10)} |`;
  });
  return [
    "---",
    `period: ${file.period}`,
    `company: ${file.company}`,
    `reports: [${codes.join(", ")}]`,
    "---",
    "",
    `# Period ${file.period}`,
    "",
    `Imported TOPSIM reports (${codes.length} of 16). Generated by topsim-copilot on every import, so edit the`,
    `data in the app, not here. Full parsed values and raw text: \`data/period-${file.period}.json\`.`,
    "",
    "| Code | Report | Imported |",
    "|---|---|---|",
    ...rows,
    "",
  ].join("\n");
}
